---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-shared-pv
  labels:
    type: nfs
    part-of: registry
    env: tests
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  NFS:
    server: nfs-server.local
    path: "/export/tests/registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-shared-pvc
  labels:
    type: nfs
    part-of: registry
    env: tests
spec:
  selector:
    type: nfs
    part-of: registry
    env: tests
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
