apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-gc-config
  labels:
    app: registry-gc
    part-of: registry
    env: tests
data:
  config.yml: |
    version: 0.1
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: registry-gc
  labels:
    app: registry-gc
    part-of: registry
    env: tests
spec:
  jobTemplate:
    metadata:
      name: registry-gc
      labels:
        app: registry-gc
        part-of: registry
        env: tests
    spec:
      template:
        metadata:
          labels:
            app: registry-gc
            part-of: registry
            env: tests
        spec:
          containers:
          - image: registry:2.7.1
            name: registry-gc
            command:
              - "/bin/registry"
            args:
              - garbage-collect
              - /conf/config.yml
            resources:
              cpu:
                requests: "0.25"
                limits: "0.25"
              memory:
                requests: 512Mi
                limits: 512Mi
            volumeMounts:
            - name: registry-gc-conf
              mountPath: "/conf"
            - name: registry-fs
              mountPath: "/var/lib/registry"
          volumes:
          - name: registry-gc-conf
            configMap:
              name: registry-gc-config
          - name: registry-fs
            persistentVolumeClaim:
              claimName: registry-shared-pvc
          restartPolicy: OnFailure
  schedule: 0 5 * * ?
