apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  labels:
    {{- include "hiring-test-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc | quote }}
  postgres-password: {{ randAlphaNum 16 | b64enc | quote }}
  replication-password: {{ randAlphaNum 16 | b64enc | quote }}
