apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: registry-tls-internal
  labels:
    app: registry
    part-of: registry
    env: tests
    usage: internal
data:
  tls.crt: AAAAAAAA
  tls.key: XXXXXXXX
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
    part-of: registry
    env: tests
  name: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
      part-of: registry
      env: tests
  template:
    metadata:
      labels:
        app: registry
        part-of: registry
        env: tests
    spec:
      containers:
      - name: registry
        image: registry:2.7.1
        env:
        - name: STORAGE_DELETE_ENABLED
          value: "true"
        - name: REDIS_ADDR
          value: "registry-cache.svc"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-cache-password
              key: password
              optional: false
        - name: HTTP_ADDR
          value: "0.0.0.0:443"
        - name: HTTP_TLS_CERTIFICATE
          value: "/tls/tls.crt"
        - name: HTTP_TLS_KEY
          value: "/tls/tls.key"
        - name: HTTP_DEBUG_ADDR
          value: "0.0.0.0:5001"
        livenessProbe:
          httpGet:
            port: 5001
            scheme: HTTP
            path: "/debug"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 4Gi
        volumeMounts:
        - name: registry-tls
          mountPath: "/tls"
        - name: registry-fs
          mountPath: "/var/lib/registry"
      volumes:
      - name: registry-tls
        secret: 
          secretName: registry-tls-internal
          optional: false
      - name: registry-fs
        persistentVolumeClaim:
          claimName: registry-shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
    part-of: registry
    env: tests
  name: registry
spec:
  ports:
  - name: registry-https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: registry
    part-of: registry
    env: tests
  type: ClusterIP
