---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaosMonkey
  namespace: default
  labels:
    tier: test-assignment
    part-of: cmonkey
rules:
  - apiGroups: v1
    resources: ['pods']
    verbs: ['list', 'get', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaosMonkey
  namespace: default
  labels:
    tier: test-assignment
    part-of: cmonkey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaosMonkey
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: chaosMonkey
